* Tomato-timer
A tomato-timer using pomodoro technique. Use the built-in =notifications= library.
** Installation
Download the repository, then

#+begin_src elisp
(load "/path/to/tomato-timer.el")
(require 'tomato-timer)
#+end_src

** Usage
=M-x Tomato-timer= . This function will start a new tomato timer.

Use =list-timers= to show all timer. If you want to close a tomato timer, put
your point in the entry, press =c= will cancel it.
** Customization
- =tomato-timer-play-sound-p= : whether play sound when a tomato-timer
  ends. Default is =t= , set to nil to make it silent.
- =tomato-timer-audio-file-path= : the path of alert audio file. Default is the
  plugin directory.
- =tomato-timer-audio-player= : the audio player to play the alert
  audio. Default is mpv.
- =tomato-timer-mpv-args= : the extra mpv arguments. Default is =--no-config= in
  order to avoid conflict with your other fancy mpv configurations.
- =tomato-timer-work-time= : the time in minutes for a tomato-timer
  period. Default is =25=.
- =tomato-timer-show-modeline-indicator-p= : whether show timer indicator in
  modeline. Default is =t=, set =nil= will not show indicator.
- =tomato-timer-notification-title= : the title of the notification. Default is
  =Tomato ends= .
- =tomato-timer-notification-body=  : the body of the notification. Default is
  =<NUMBER> min passed, take a break!= .
- =tomato-timer-mode-line-indicator-delimiter= : the delimiter of the mode line
  indicator. It is a list contains two string elements, first is the left delimiter,
  and the second is the right delimiter. Default is ='("" "")= .
** Credit
The mode line indicator is modified from syohex's [[https://github.com:/syohex/emacs-mode-line-timer][emacs-mode-line-timer]].

